name: Terraform GCP Deploy

on:
  push:
    branches: [main]

jobs:
  terraform:
    name: Deploy com Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Autenticar na GCP com conta de serviço
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Inicializar Terraform
        run: terraform init

      - name: Validar Terraform
        run: terraform validate

      - name: Terraform import
        run: ./terraform-import-resources.sh

      - name: Terraform destroy
        run: terraform destroy -auto-approve
 
      - name: Aplicar Terraform (auto-approve)
        run: terraform apply -auto-approve
        env:
         TF_VAR_gcp_credentials: ${{ secrets.GCP_CREDENTIALS }}
         TF_VAR_project_id: ${{ secrets.PROJECT_ID }}
